### ISSUE TITLE
Add upcoming events section

### ISSUE THREAD

**Issue by redisforlosers** [CodeForFoco/codeforfoco.github.io#90]
- [ ] embed [MeetUp Widget](https://codeforfoco.slack.com/archives/C3XB56E3A/p1493949991085374) below header area but above the fold

**Comment by JordanMajd** [comment]
Let's put relevant information on github, so people don't need access to our slack for visibility.


[Meetup's Widget Foundry](https://www.meetup.com/meetup_api/foundry/) can be used to create a widget for the group to display upcoming events. The standard one is a simple iFrame, however you can generate editable ones.

```html
<iframe width="225" height="570" src="http://meetu.ps/2YMMdn" frameborder="0"></iframe>
```

**Comment by davidbhayes** [comment]
FYI: @abettermap has a pretty good slightly-more-configurable-than-an-iframe iteration of this somewhat built

**Comment by abettermap** [comment]
@davidbhayes 

I made some progress on the `<iframe>` alternative this weekend. Maybe not the best Jekyll approach, but it's in there ([branch](https://github.com/CodeForFoco/codeforfoco.github.io/tree/90/upcoming-events)). Needs some polishing obviously, then I'll PR, but so far I've got it on home page:

![image](https://user-images.githubusercontent.com/4974087/28761678-a409efa0-756d-11e7-85d5-8e1aead4ff6f.png)

...and its own page:

![image](https://user-images.githubusercontent.com/4974087/28761695-c2d47766-756d-11e7-84bc-da18609173b1.png)

I'm using my own API key but maybe we can get one from @JordanMajd since the Meetup is on his acct.

**Comment by davidbhayes** [comment]
Looks great! Unimaginably more native than an iframe. 

My biggest thought looking at it is that the labels and the dates don't form clear pairs when I look at it. Borders and/or more spacing between the non-related things would help. But otherwise I think it's basically merge-able. (Though I admit I didn't thoroughly audit all the commits. ;p)

**Comment by JordanMajd** [comment]
Good work, look forward to the PR

**Comment by abettermap** [comment]
@davidbhayes 

I didn't really touch the styling yet, hopefully have something tonight.
