### ISSUE TITLE
Create site architecture diagram

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/codeforfoco.github.io#91]
Sitemap/whatever to describe the site layout. Makes it easier to structure code and links, etc.

- [ ] screenshot in readme
- [ ] link to original in readme

**Comment by JordanMajd** [comment]
Just to clarify, you are looking for an actual diagram and not the [sitemap.xml](http://codeforfoco.org/sitemap.xml)?

**Comment by abettermap** [comment]
Yep. Even just a whiteboard sketch or google doc or something. 

A lot of the issues and suggestions for the site involve new content and where to put it, so I think an outline would be useful. 

I should be able to work on this today and get some feedback from you and the group when I'm done.

**Comment by JordanMajd** [comment]
:thumbsup:

**Comment by abettermap** [comment]
Illegible refrigerator draft: ✅. On to high-tech...

![img_0688](https://cloud.githubusercontent.com/assets/4974087/26028791/96dbfc54-37e4-11e7-8724-86125d5347dd.JPG)

**Comment by abettermap** [comment]
Ok gave it a shot with Lucidchart. Read-only published version is [here](https://www.lucidchart.com/documents/view/eb916f30-ba86-417d-bb4a-999b6c558274) and I will post the edit link in Slack if anyone wants to add comments, notes, or edits.

**Comment by abettermap** [comment]
Great Yoast article on site structure: https://yoast.com/site-structure-seo/

**Comment by JordanMajd** [comment]
This looks great and is something that is definitely needed. The site has been improving with time, but still leaves a lot to be desired. The site is not organized, lacks content and isn't the greatest user experience. A chart like this will help solve many of those problems and provide a model to work towards.


I like how the categories are arranged by "thought", i.e. "Get Involved". 

We should add an image of the lucid chart to the README, even if it isn't perfect yet, so that there is a reference for us to start working towards. Then we should start fleshing out a plan to start moving the site in that direction. As we do that we can keep iterating on this design chart.
